#Arrays Using numpy

In [2]:
import numpy as np

a = np.array([1,2,3,5,7],dtype='i')

b = np.array((2,3,5),dtype='f')

print(a)
print(type(a))
print(a[0:2])

print(b)
print(type(b))
print(b[1:2])

[1 2 3 5 7]
<class 'numpy.ndarray'>
[1 2]
[2. 3. 5.]
<class 'numpy.ndarray'>
[3.]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

print(type(a))
print(a)

print(a[0])

print(a[0,2])
print(a[1,1])

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[1 2 3]
3
5


In [11]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

print(type(c))
print(c)

<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 0  0 -1]]

 [[-1 -2 -3]
  [-4 -5 -6]
  [ 0  0  1]]]


In [13]:

print(c.shape)
print(c.shape[0])
print(c.shape[1])
print(c.shape[2])



(2, 3, 3)
2
3
3


In [ ]:
A = np.arange(20,100,3) # for i in range(20,100,3)
print(A)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [ ]:
print(range(10))

range(0, 10)


In [ ]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
A = np.random.permutation(np.arange(10))
print(A)

[9 2 7 5 1 6 4 8 0 3]


In [14]:
A = np.random.rand(300)

print(type(A))
print(A.shape)


print(A)

<class 'numpy.ndarray'>
(300,)
[0.71651953 0.87622216 0.72789517 0.04067964 0.36265971 0.17401372
 0.39548196 0.1698965  0.99406234 0.37142486 0.0187279  0.29743995
 0.63554569 0.05096127 0.74080794 0.15184863 0.86781918 0.50527365
 0.1823721  0.7552468  0.71187905 0.88583209 0.14141031 0.34699733
 0.29620191 0.29245444 0.02892625 0.83280634 0.33702297 0.56365818
 0.17434927 0.27672758 0.88576758 0.42189306 0.45580713 0.29035176
 0.13202111 0.01101302 0.64881487 0.05067847 0.19394745 0.14310215
 0.25308924 0.82874094 0.52366357 0.4198116  0.409229   0.23827019
 0.25985686 0.67850564 0.02162034 0.28328139 0.18015314 0.70240038
 0.22697946 0.95192316 0.50402583 0.86214749 0.43296141 0.13342258
 0.36678243 0.22866494 0.10592184 0.5299946  0.7749809  0.95315068
 0.1582479  0.92896317 0.59248488 0.57911105 0.51385135 0.66746597
 0.74571787 0.68360036 0.22301993 0.88759681 0.83771752 0.72745574
 0.49395719 0.99807844 0.961528   0.64884786 0.63738527 0.53634709
 0.8823859  0.64603122 0.921189

In [16]:
v = np.random.rand(20,300)

print(type(v))
print(v.shape)
print(v)



<class 'numpy.ndarray'>
(20, 300)
[[0.64068306 0.07371293 0.99349081 ... 0.72567649 0.31160547 0.91711094]
 [0.57834616 0.58214154 0.56810898 ... 0.1782193  0.89608656 0.57575698]
 [0.32272783 0.23121249 0.28385008 ... 0.32009175 0.29928679 0.73902992]
 ...
 [0.24413629 0.2870857  0.9372614  ... 0.66662701 0.77628667 0.14538792]
 [0.63825539 0.24181396 0.34198283 ... 0.26516154 0.40927612 0.16479261]
 [0.39267001 0.52840012 0.65825005 ... 0.82212884 0.44842388 0.17595937]]
