#Data Frames  using Pandas

In [203]:
import pandas as pd
import numpy as np

print(pd.__version__)

1.1.5


In [204]:
A = pd.Series([2,3,4,5],index=['a','b','c','d'])

print(A)

print(A.values)

a    2
b    3
c    4
d    5
dtype: int64
[2 3 4 5]


In [205]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

print(grads)

print(grads.values)

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64
[4.  3.5 3.  2.5]


In [206]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

print(marks)

print(marks.keys)

print(marks.values)

A    85
B    75
C    65
D    55
dtype: int64
<bound method Series.keys of A    85
B    75
C    65
D    55
dtype: int64>
[85 75 65 55]


In [207]:
D = pd.DataFrame({'Marks':marks,'Grades':grads})

print(D)

print("Transpose of D")
print(D.T)

print("Keys")
print(D.keys)

print("Values")
print(D.values)

print("Colums")
print(D.columns)

   Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5
Transpose of D
           A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5
Keys
<bound method NDFrame.keys of    Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5>
Values
[[85.   4. ]
 [75.   3.5]
 [65.   3. ]
 [55.   2.5]]
Colums
Index(['Marks', 'Grades'], dtype='object')


In [208]:
print("Adding new column")
D['ScaledMarks'] = 100*(D['Marks']/90)

print(D)

print(D.columns)

Adding new column
   Marks  Grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111
Index(['Marks', 'Grades', 'ScaledMarks'], dtype='object')


In [209]:
print("Print the table")

D

Print the table


Marks  Grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111

In [210]:
print("Searching for Marks > 70")
G = D[D['Marks']>70]

print(G)

Searching for Marks > 70
   Marks  Grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333


##Slicing

In [212]:
# Initializing the nested list with Data set
player_list = [['M.S.Dhoni', 36, 75, 5428000], 
               ['A.B.D Villers', 38, 74, 3428000], 
               ['V.Kholi', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000], 
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]
  
# creating a pandas dataframe
df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
  
# data frame before slicing
df

Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kholi   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [213]:
df1 = df.iloc[:,:]

df1

Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kholi   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [214]:
# Slicing rows in data frame
df1 = df.iloc[1:4]
  
# data frame after slicing
df1

Name  Age  Weight   Salary
1  A.B.D Villers   38      74  3428000
2        V.Kholi   31      70  8428000
3        S.Smith   34      80  4428000

In [215]:
# Slicing columns in data frame
df1 = df.iloc[:,1:3]
  
# data frame after slicing
df1

Age  Weight
0   36      75
1   38      74
2   31      70
3   34      80
4   40     100
5   33      72
6   42      85

In [216]:
# Slicing rows and columns in data frame
df1 = df.iloc[1:4,1:3]

df1

Age  Weight
1   38      74
2   31      70
3   34      80

In [217]:
# Specific row
print("3rd row")
df.iloc[2,:]

3rd row


Name      V.Kholi
Age            31
Weight         70
Salary    8428000
Name: 2, dtype: object

In [218]:
# Specific column
print("3rd colum")
df.iloc[:,2]

3rd colum


0     75
1     74
2     70
3     80
4    100
5     72
6     85
Name: Weight, dtype: int64

In [219]:
print("Reversing the table")
df.iloc[::-1,:]

Reversing the table


Name  Age  Weight   Salary
6     K.Peterson   42      85  2528000
5         J.Root   33      72  7028000
4        C.Gayle   40     100  4528000
3        S.Smith   34      80  4428000
2        V.Kholi   31      70  8428000
1  A.B.D Villers   38      74  3428000
0      M.S.Dhoni   36      75  5428000

In [220]:
print("Last column values")
df.iloc[::,-1]

Last column values


0    5428000
1    3428000
2    8428000
3    4428000
4    4528000
5    7028000
6    2528000
Name: Salary, dtype: int64

##Filling Missing values

In [221]:
# dictionary of lists
dict = {'First Score':[100, 90, 85, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[56, 40, 80, 98],
        'Fourth Score': [23,45,np.nan,76],
        'Fifth Score': [54,76,92,np.nan],
        'Sixth Score': [np.nan,53,67,59]}
  
# creating a dataframe from dictionary
df = pd.DataFrame(dict)

df

First Score  Second Score  ...  Fifth Score  Sixth Score
0          100          30.0  ...         54.0          NaN
1           90          45.0  ...         76.0         53.0
2           85          56.0  ...         92.0         67.0
3           95           NaN  ...          NaN         59.0

[4 rows x 6 columns]

In [222]:
# using isnull() function  
df.isnull()

First Score  Second Score  ...  Fifth Score  Sixth Score
0        False         False  ...        False         True
1        False         False  ...        False        False
2        False         False  ...        False        False
3        False          True  ...         True        False

[4 rows x 6 columns]

In [223]:
# using notnull() function 
df.notnull()

First Score  Second Score  ...  Fifth Score  Sixth Score
0         True          True  ...         True        False
1         True          True  ...         True         True
2         True          True  ...         True         True
3         True         False  ...        False         True

[4 rows x 6 columns]

In [225]:
print("Filling missing values using column")
df['Second Score'] = df['Second Score'].fillna(0)

df

Filling missing values using column


First Score  Second Score  ...  Fifth Score  Sixth Score
0          100          30.0  ...         54.0          NaN
1           90          45.0  ...         76.0         53.0
2           85          56.0  ...         92.0         67.0
3           95           0.0  ...          NaN         59.0

[4 rows x 6 columns]

In [226]:
df['Fourth Score'] = df['Fourth Score'].replace(np.nan, 0)

df

First Score  Second Score  ...  Fifth Score  Sixth Score
0          100          30.0  ...         54.0          NaN
1           90          45.0  ...         76.0         53.0
2           85          56.0  ...         92.0         67.0
3           95           0.0  ...          NaN         59.0

[4 rows x 6 columns]

In [227]:
# using notnull() function 
df.notnull()

First Score  Second Score  ...  Fifth Score  Sixth Score
0         True          True  ...         True        False
1         True          True  ...         True         True
2         True          True  ...         True         True
3         True          True  ...        False         True

[4 rows x 6 columns]

In [228]:
print("Filling missing values in the entire table using fillna or replace")
df = df.replace(np.nan,0)

df

Filling missing values in the entire table using fillna or replace


First Score  Second Score  ...  Fifth Score  Sixth Score
0          100          30.0  ...         54.0          0.0
1           90          45.0  ...         76.0         53.0
2           85          56.0  ...         92.0         67.0
3           95           0.0  ...          0.0         59.0

[4 rows x 6 columns]

In [229]:
print("Filling missing values in the entire table using fillna or replace")
df = df.fillna(0)

#df.replace(np.nan,0)
df

Filling missing values in the entire table using fillna or replace


First Score  Second Score  ...  Fifth Score  Sixth Score
0          100          30.0  ...         54.0          0.0
1           90          45.0  ...         76.0         53.0
2           85          56.0  ...         92.0         67.0
3           95           0.0  ...          0.0         59.0

[4 rows x 6 columns]

##Dropping Missing Values

In [231]:
# dictionary of lists
dict = {'First Score':[100, 90, 85, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[56, 40, 80, 98],
        'Fourth Score': [23,45,76,np.nan],
        'Fifth Score': [54,76,92,np.nan]}
  
# creating a dataframe from dictionary
df1 = pd.DataFrame(dict)

df1

First Score  Second Score  Third Score  Fourth Score  Fifth Score
0          100          30.0           56          23.0         54.0
1           90          45.0           40          45.0         76.0
2           85          56.0           80          76.0         92.0
3           95           NaN           98           NaN          NaN

In [232]:
# using dropna() function withput specificing axis  
df1.dropna()

df1

First Score  Second Score  Third Score  Fourth Score  Fifth Score
0          100          30.0           56          23.0         54.0
1           90          45.0           40          45.0         76.0
2           85          56.0           80          76.0         92.0
3           95           NaN           98           NaN          NaN

In [233]:
# using dropna() function to drop rows having na      
df1.dropna(axis = 0)

First Score  Second Score  Third Score  Fourth Score  Fifth Score
0          100          30.0           56          23.0         54.0
1           90          45.0           40          45.0         76.0
2           85          56.0           80          76.0         92.0

In [234]:
# making new data frame with dropped NA values 
new_df1 = df1.dropna(axis = 0, how ='any') 
    
new_df1

First Score  Second Score  Third Score  Fourth Score  Fifth Score
0          100          30.0           56          23.0         54.0
1           90          45.0           40          45.0         76.0
2           85          56.0           80          76.0         92.0

In [235]:
# using dropna() function to drop columns having na      
df1.dropna(axis = 1)

First Score  Third Score
0          100           56
1           90           40
2           85           80
3           95           98

In [236]:
# using dropna() function to drop columns having na      
new_dfc = df1.dropna(axis = 1)

new_dfc

First Score  Third Score
0          100           56
1           90           40
2           85           80
3           95           98